### ISSUE TITLE
No auto tap?

### ISSUE THREAD

**Issue by tuanteku9x** [mudachyo/BUMP#2]
Hi pro, it's working?. I see nothing happened

**Comment by khosrowkhazraei** [comment]
same here, it does not perform auto tap

**Comment by khosrowkhazraei** [comment]
so, i planned bor, here is the script :

// ==UserScript==
// @name         BUMP Autoclicker
// @version      1.0
// @description  Automatically clicks the button in the popup every second
// @author       mudachyo
// @match        *://mmbump.pro/*
// @run-at       document-start
// @icon         https://sun9-16.userapi.com/impg/g93WJxPJtCopVIAqWbzvaGWbkn-LaY-pEyCh1Q/Jvut2jMz7Rc.jpg?size=640x640&quality=95&sign=2f4460fee947b101894f4c274a599bff&c_uniq_tag=hQ43e9wzpBH6S4E0mWytfXtp5gde33mgCvmnGLVj-rI&type=album
// @grant        none
// @downloadURL  https://github.com/mudachyo/BUMP/raw/main/bump-autoclicker.user.js
// @updateURL    https://github.com/mudachyo/BUMP/raw/main/bump-autoclicker.user.js
// @homepage     https://github.com/mudachyo/BUMP
// ==/UserScript==

(function() {
    'use strict';

    // Styles for logs
    const styles = {
        success: 'background: #28a745; color: #fff; font-weight: bold; padding: 4px 8px; border-radius: 4px;',
        starting: 'background: #8640ff; color: #fff; font-weight: bold; padding: 4px 8px; border-radius: 4px;',
        error: 'background: #dc3545; color: #fff; font-weight: bold; padding: 4px 8px; border-radius: 4px;',
        info: 'background: #007bff; color: #fff; font-weight: bold; padding: 4px 8px; border-radius: 4px;'
    };

    const logPrefix = '%c[BUMP Bot] ';
    const originalLog = console.log;
    console.log = function () {
        if (typeof arguments[0] === 'string' && arguments[0].includes('[BUMP Bot]')) {
            originalLog.apply(console, arguments);
        }
    };

    console.error = console.warn = console.info = console.debug = () => {};

    console.clear();
    console.log(`${logPrefix}Starting`, styles.starting);
    console.log(`${logPrefix}Created by https://t.me/mudachyo`, styles.starting);
    console.log(`${logPrefix}Github https://github.com/mudachyo/BUMP`, styles.starting);

    // Function to simulate a touch event on a specific element
    function simulateTouch(element) {
        const rect = element.getBoundingClientRect();
       const offsetX = Math.random() * rect.width;
    const offsetY = Math.random() * rect.height;
        const touch = new Touch({
            identifier: Date.now(),
            target: element,
            clientX: rect.left + offsetX / 2,
            clientY: rect.top + offsetY / 2,
            screenX: rect.left + rect.width / 2,
            screenY: rect.top + rect.height / 2,
            pageX: rect.left + rect.width / 2,
            pageY: rect.top + rect.height / 2,
            radiusX: 2.5,
            radiusY: 2.5,
            rotationAngle: 10,
            force: 0.5,
        });

        let touchEvent = new TouchEvent('touchstart', {
            cancelable: true,
            bubbles: true,
            touches: [touch],
            targetTouches: [touch],
            changedTouches: [touch],
        });

        element.dispatchEvent(touchEvent);

        touchEvent = new TouchEvent('touchend', {
            cancelable: true,
            bubbles: true,
            touches: [touch],
            targetTouches: [],
            changedTouches: [touch],
        });

        element.dispatchEvent(touchEvent);
    }

    // Function to repeatedly find and touch the button every second
    function autoTouchButton() {
        const button = document.querySelector('.styled__Tap-sc-1lbly2t-10');
        if (button) {
            simulateTouch(button);
            console.log(`${logPrefix}Button touched!`, styles.success);
        } else {
            console.log(`${logPrefix}Button not found, retrying...`, styles.error);
        }
        setTimeout(autoTouchButton, 100); // Retry every second
    }

    // Start the auto touch button function after a delay
    setTimeout(autoTouchButton, 3000);

})();
